### ISSUE TITLE
Tistema de tickets

### ISSUE THREAD

**Issue by PokeToribio** [PokeToribio/VozLiveBot#20]
Todos sabemos que tengo envidia de potato, asi que yo tambien quiero hacer un sistema de tickets 👍

**Comment by PokeToribio** [comment]
Investigar como hacer para que cuando se cierre el ticket quede un log

**Comment by ThePotatoCamera** [comment]
> Todos sabemos que tengo envidia de potato, asi que yo tambien quiero hacer un sistema de tickets +1

¿Alguien me ha llamado?

**Comment by PokeToribio** [comment]
Abandono la idea, demasiado dificil para mi actualmente
